o2Labs/office-booker

- README.md
- build.sh
- client/package.json
- client/yarn.lock
- Include information about release plan in readme.
- Fix client audit errors (using manual resolution overrides)
- Test all client packages as using webpack could include devDependencies in the build output.
> Docs updates

- build.sh
- server/app-config.ts
- server/bookings/createBooking.ts
- server/bookings/deleteBooking.ts
- server/bookings/model.ts
- server/db/bookings.ts
- server/db/officeBookings.ts
- server/getOffices.ts
- server/scripts/create-dynamo-tables.ts
- server/tests/admin-users.test.ts
- server/tests/all-users.test.ts
- server/tests/api-anon.test.ts
- server/tests/non-admin-users.test.ts
- server/tests/office-admin-users.test.ts
- server/tests/test-utils.ts
- test.sh
- Introducing an API to handle car parking spaces
> Parking api

- client/src/lib/api.ts
- server/auth.ts
- server/errors.ts
- server/tests/api-anon.test.ts
- server/tests/test-utils.ts
- Use HttpError class and standard error handling middleware.
Closes #13
> Use standard Authorization header

- client/src/components/Structure.tsx
- client/src/components/TestBanner.styles.ts
Wrapped within the `<Layout></Layout>` component.  Removes a front-end "flicker" as the view changes, due to the layout being included on subsequent views as well.
> Client config loading state

- client/src/components/Auth/EnterCode.tsx
- client/src/components/Auth/EnterEmail.tsx
- client/src/components/Auth/RequireLogin.tsx
Depends on #17 
Closes #16 
Just auto-reloading for now rather than showing a button to click.
> Login errors

- README.md
- client/src/lib/auth.ts
- server/app-config.ts
- server/local.ts
> 11 local testing without cognito

- client/src/components/App/Admin/ManageUsers.styles.ts
- client/src/components/App/Admin/Users.tsx
- client/src/lib/api.ts
- client/src/types/api.ts
- server/app.ts
- server/db/users.ts
- server/tests/admin-users.test.ts
- server/users/queryUsers.ts
- start.sh
Fixes #32 
Not super pretty, could probably improve this whole user management area at some point, but this gives a little more visibility of people actually using the system - might be quicker than having to search elsewhere for an email address.
> List all users

- client/src/components/App/Home/MakeBooking.styles.ts
- client/src/components/App/Home/MakeBooking.tsx
> added change office redirect into make booking just like help page.

- infrastructure/index.ts
Have deployed already to test this fixes the permissions issue when fetching all registered users.
> Allow listing of users from the http lambda

- client/src/components/App/UpcomingBookings.styles.ts
- client/src/components/App/UpcomingBookings.tsx
> separated previous bookings from upcoming bookings in a list.

- README.md
- client/src/components/App/UpcomingBookings.tsx
- client/src/lib/api.ts
- client/src/lib/auth.ts
- server/app-config.ts
- server/local.ts
- Upcoming bookings filtering
- Local config parsing
- Test auth parsing
> General refactorings

- client/src/lib/auth.ts
Short-term workaround related to #57
> Make email lowercase

- client/src/components/App/Admin/Bookings.tsx
- client/src/components/App/Admin/CreateBooking.tsx
- client/src/components/App/Home/MakeBooking.styles.ts
- client/src/components/App/Home/MakeBooking.tsx
- client/src/components/App/UpcomingBookings.styles.ts
- client/src/components/App/UpcomingBookings.tsx
- client/src/components/App/ViewBooking.styles.ts
- client/src/components/App/ViewBooking.tsx
- client/src/components/Assets/BookButton.styles.ts
- client/src/components/Assets/BookButton.tsx
- client/src/components/Assets/BookingStatus.styles.ts
- client/src/components/Assets/BookingStatus.tsx
- client/src/components/Layout/Header.styles.ts
Mainly styling around the home screens:
- View booking
- Upcoming bookings
- Create booking to use global alerts
- Fix bookings cancel refresh
- General app-level styling
Will close https://github.com/o2Labs/office-booker/issues/42
> 42 home styling

- client/src/components/App/UpcomingBookings.tsx
> 64 view booking list should show parking choice

- client/src/components/App/Admin/Bookings.tsx
- client/src/components/App/Admin/Layout/Header.styles.ts
- client/src/components/App/Admin/Layout/Header.tsx
- client/src/components/App/Help.tsx
- client/src/components/App/Home.tsx
- client/src/components/App/Home/MakeBooking.styles.ts
- client/src/components/App/Home/MakeBooking.tsx
- client/src/components/App/Home/WhichOffice.tsx
- client/src/components/AppProvider.tsx
- client/src/context/reducers.ts
- client/src/context/stores.ts
- client/src/styles/MaterialComponents.ts
Closes https://github.com/o2Labs/office-booker/issues/66, https://github.com/o2Labs/office-booker/issues/68 and https://github.com/o2Labs/office-booker/issues/69.
> 68 refresh content

- client/src/components/App/Admin/Bookings.styles.ts
- client/src/components/App/Admin/Bookings.tsx
> 73 add count to admin bookings list

- client/src/components/App/Home/MakeBooking.tsx
> removed out conditional on same day booking so user can book two offices on one day.

- client/src/components/App/Home/MakeBooking.tsx
> Fix after weekend view bug

- client/src/lib/api.ts
- client/src/lib/auth.ts
- infrastructure/index.ts
- server/app.ts
- server/bookings/createBooking.ts
- server/bookings/model.ts
- server/db/users.ts
- server/tests/admin-users.test.ts
- server/tests/all-users.test.ts
- server/tests/api-anon.test.ts
- server/tests/office-admin-users.test.ts
- server/users/model.ts
- server/users/putUser.ts
- server/users/register.ts
Validate and normalise email addresses server-side
- We can then disable public sign-ups in the future
- All users will now be created in DynamoDB
> Do user registrations via the API

- client/src/components/App/Home.styles.ts
- client/src/components/App/Home.tsx
> implemented banner for IE users encouraging them to use modern browsers.

- deploy.sh
Minor fix from first deployment test
> Fix paths in deploy script

- deploy.sh
- infrastructure/index.ts
- server/db/officeBookings.ts
- server/migrations/2-replace-office-booking-ids.ts
- server/migrations/index.ts
- server/tests/migrations.test.ts
> 102 office booking migration

- server/app-config.ts
- server/local.ts
- server/migrations/1-save-users-to-db.ts
- server/tests/migrations.test.ts
- server/tests/test-utils.ts
> User migration

- infrastructure/index.ts
- server/db/bookingsV2.ts
- server/migrations/3-move-bookings.ts
- server/scripts/create-dynamo-tables.ts
- server/tests/migrations.test.ts
- server/tests/test-utils.ts
Fixes #103
Migration path:
1. Create new table
2. Copy all rows from old table into new table, switch to use officeId
`bookingsV2.ts` is basically a copy of `bookings.ts`, just pointing to the new table and therefore using `officeId`.
> Create bookings migration

- CHANGELOG.md
- infrastructure/index.ts
- server/app.ts
- server/migrations/index.ts
- Set API to readonly until next major version is deployed.
> Enable office bookings migrations

- server/bookings/deleteBooking.ts
- server/bookings/model.ts
- server/tests/non-admin-users.test.ts
- server/tests/office-admin-users.test.ts
> 66 disable cancel booking on api

- client/src/components/App/Admin/Bookings.test.tsx
- client/src/components/Auth/Auth.test.tsx
- client/src/components/Auth/EnterCode.tsx
- client/src/components/Auth/EnterEmail.tsx
- client/test/handlers.ts
- client/test/server.mock.ts
Add tests for stepping through the login process.
> Client auth interaction tests

- client/src/components/App/Admin/BookingStats.tsx
- client/src/components/App/Admin/Layout/Header.tsx
- client/src/components/Routes.tsx
- client/src/lib/api.ts
- client/src/types/api.ts
- server/app.ts
- server/bookings/createBooking.ts
- server/bookings/deleteBooking.ts
- server/dates.ts
- server/getOffices.ts
- server/local.ts
- server/stats.ts
- server/tests/admin-users.test.ts
- server/tests/dates.test.ts
Just a very simple page to show all current booking stats per office, per day.
> Office stats

- client/package.json
- client/src/components/App/Home.test.tsx
- client/src/components/App/Home.tsx
- client/src/components/Auth/Auth.test.tsx
- client/src/components/Auth/EnterCode.tsx
- client/src/components/Auth/EnterEmail.tsx
- client/src/components/Layout/Header.tsx
- client/src/components/Routes.tsx
- client/test/data.ts
- client/test/handlers.ts
- client/yarn.lock
Various minor accessibility and usability tweaks.
- Use "Sign in/out" everywhere instead of sometimes "login".
- Better button verbs rather than just "submit".
- Auto-focus verification code input.
- Separate admin pages out of main bundle.
- Add missing alt text for logos.
- Remove IE banner when not displaying it (don't just hide with CSS).
> Accessibility tweaks

- client/src/components/App/Admin/CreateBooking.tsx
- client/src/components/App/Home/MakeBooking.tsx
- client/tsconfig.json
- client/yarn.lock
- Use simple index to track selected week.
- Identify weeks by the first day of the week as a date rather than the week number.
> Fix issue with dates showing up after new year

- infrastructure/index.ts
- server/app-config.ts
- server/app.ts
- server/bookings/createBooking.ts
- server/bookings/model.ts
- server/tests/booking.test.ts
Updated with the following
- include extra env fields in infrastructure index
- include extra env fields available in app config
- include reason field in booking
- logic to send reason notifications to configured email address
> 128 new booking notification

- client/package.json
- client/yarn.lock
To bypass audit warning for deployment https://github.com/facebook/create-react-app/issues/10411#issuecomment-781399779
> Upgrading react-scripts and adding immer resolution

- .github/workflows/build.yml
- build.sh
- client/yarn.lock
- infrastructure/package.json
- infrastructure/yarn.lock
Upgrade infrastructure packages
- Upgrade major Pulumi versions.
- Upgrade all other minor package versions.
Upgrade client packages
- Upgrade all minor version changes.
- Ignore dev dependencies when auditing the client.
> Package upgrades

- .gitignore
- README.md
- client/src/styles/MaterialTheme.ts
- infrastructure/cognito/createAuthChallenge.ts
- infrastructure/cognito/defineAuthChallenge.ts
- infrastructure/cognito/preSignUp.ts
- infrastructure/cognito/verifyAuthChallengeResponse.ts
- infrastructure/index.ts
> Add before/after first deploy instructions
